// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  categoryblogger: dynamic(() => import("./Categoryblogger")),
  editors_pick: dynamic(() => import("./EditorsPickSlice")),
  feature_blog: dynamic(() => import("./FeatureBlog")),
};
